### PR TITLE
#6 Scroll to top when changing page

### PR DESCRIPTION
**Pull request by scastiel**
There is no clean way to scroll to the top in a pure-React/Redux way, so I guess it's a good idea to do it after fetching the results in the action creator as a side-effect.

### CODE REVIEW

**Comment by mac-s-g** [comment]
thank you for contributing!
i dig the update.  i'll test it out as soon as I have a few minutes

**Comment by mac-s-g** [comment]
i like this a lot.  it's really smooth.  my only issue is that the scroll happens at page load with the initial query.  what do you think is best way to address that?  I'm gonna leave this open for now.

**Comment by mac-s-g** [comment]
@scastiel i updated the logic a bit such that scroll only triggers with page select.

updates are committed to `scastiel/scroll-to-top`

you want to review or test before I merge?

**Comment by scastiel** [comment]
Hi! I won't have time to test today, but it looks good to me. If it's okay for you then it is for me ;)

**Pull request merged**
